USE O_SYDOR_MODULE_3

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'supplies' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.supplies;
GO

CREATE TABLE dbo.supplies
	(
	supplierid int NOT NULL,
	detailid int NOT NULL,
	productid int NOT NULL,
	quantity int NOT NULL
	)  ON [PRIMARY]
GO

COMMIT

BEGIN TRANSACTION
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'suppliers' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.suppliers;
GO

CREATE TABLE dbo.suppliers
	(
	supplierid int NOT NULL,
	name varchar(20) NOT NULL,
	rating int NULL,
	city varchar(20) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.suppliers ADD CONSTRAINT
	PK_suppliers PRIMARY KEY CLUSTERED 
	(
	supplierid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

COMMIT

/* CREATE TABLE DETAILS. */
BEGIN TRANSACTION
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'details' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.details;
GO

CREATE TABLE dbo.details
	(
	detailid int NOT NULL,
	name varchar(20) NOT NULL,
	color varchar(20) NOT NULL,
	weight int NOT NULL,
	city varchar(20) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.details ADD CONSTRAINT
	PK_details PRIMARY KEY CLUSTERED 
	(
	detailid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

COMMIT


/* CREATE TABLE PRODUCTS */

BEGIN TRANSACTION
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'products' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.products;
GO

CREATE TABLE dbo.products
	(
	productid int NOT NULL,
	name varchar(20) NOT NULL,
	city varchar(20) NOT NULL
	)  ON [PRIMARY]
GO

ALTER TABLE dbo.products ADD CONSTRAINT
	PK_products PRIMARY KEY CLUSTERED 
	(
	productid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

COMMIT


/* CREATE TABLE SUPPLIES */
BEGIN TRANSACTION
GO

CREATE NONCLUSTERED INDEX IX_supplier ON dbo.supplies
	(
	supplierid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_detail ON dbo.supplies
	(
	detailid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_product ON dbo.supplies
	(
	productid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

COMMIT
GO

/*Relationships */

BEGIN TRANSACTION
GO
ALTER TABLE dbo.details SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.products SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.suppliers SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
DROP INDEX IX_product ON dbo.supplies
GO
DROP INDEX IX_detail ON dbo.supplies
GO
DROP INDEX IX_supplier ON dbo.supplies
GO
CREATE NONCLUSTERED INDEX IX_supplier ON dbo.supplies
	(
	supplierid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_detail ON dbo.supplies
	(
	detailid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_product ON dbo.supplies
	(
	productid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.supplies ADD CONSTRAINT
	FK_supplies_suppliers FOREIGN KEY
	(
	supplierid
	) REFERENCES dbo.suppliers
	(
	supplierid
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.supplies ADD CONSTRAINT
	FK_supplies_products FOREIGN KEY
	(
	productid
	) REFERENCES dbo.products
	(
	productid
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.supplies ADD CONSTRAINT
	FK_supplies_details FOREIGN KEY
	(
	detailid
	) REFERENCES dbo.details
	(
	detailid
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.supplies SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* CREATE tmp_Details */
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tmp_Details' AND TABLE_SCHEMA = 'dbo')
DROP TABLE dbo.tmp_Details;
GO

SELECT TOP 0 * INTO [tmp_Details]
FROM [dbo].[details]
GO
